FROM registry.access.redhat.com/ubi8/go-toolset:1.23.6 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
  go build -a -installsuffix cgo \
  -ldflags="-s -w" \
  -o todo-api ./main.go

FROM scratch

WORKDIR /

COPY --from=builder /app/todo-api .

EXPOSE 8080

ENTRYPOINT ["./todo-api"]
